sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t marcowilm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcowilm/docker-react npm run test